---
servers:
  -
    protocol: HTTP
    socket: 'tcp://127.0.0.1:8080'
    min-children: 5
    max-children: 10
    app:
      class: MyApp
      file: MyApp.class.php
      middlewares: [PHP_Compat]
